spring:
  datasource:
    url: jdbc:mysql://192.168.1.197/007?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=CTT
    username: vortex
    password: vortex2016
    driverClassName: com.mysql.jdbc.Driver
  jpa:
   showSql: true
   hibernate:
      ddlAuto: update
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10

server:
  port: 8009