#mail
spring:
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
server:
  port: 8009


